export { About } from './about/About';
export { Contact } from './contact/Contact';
export { Experience } from './experience/Experience';
export { Footer } from './footer/Footer';
export { Header } from './header/Header';
export { Nav } from './nav/Nav';
export { Portfolio } from './portfolio/Portfolio';
export { Services } from './services/Services';
export { Testimonials } from './testimonials/Testimonials';
